name = "bolty"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-07-01"
pages_build_output_dir = "./build/client"

# Optional: اضافه کردن تنظیمات مربوط به نحوه ساخت پروژه
[build]
command = "npm run build"  # یا دستور مناسب برای پروژه شما
